# -- STATEMENT --
#
( < f2 ls / | cat | grep a && ls ) > f1
#
# -- LIST --
#
&&
||
&& ||
&& ls
ls ||
ls && ls | cat
ls | cat && ls | cat && ls | cat
ls | cat || ls | cat || ls | cat || ls | cat
ls &&
#
# -- GROUP --
#
(
)
()
( ls ) )
((((((((((((()))))))))))))
( sleep 1 | ls ) > f f2
( ls | cat )
( echo abiba > f3 )
( ( sleep 3 && sleep 1 ) | ls )
< f ( ls | cat )
> f ( ls | cat )
>> f ( ls | cat )
>> f > f1 > f2 ( ls | cat )
# echo "aboba" > f1 > f2 > f3 ls -la
#
# -- PIPELINE --
#
|
| | |
ls |
ls | cat
ls | cat | grep a | grep b | grep c | grep d
#
# -- EXPRESSION --
#
# -- REDIRECTION --
#
>
>>
<
< <
> > > > > > > > > > >
>>>>>
<<<<<
ls > f1 -la
> f1 echo hello
ls > f1
> f1 f2
> f4 > f5 > f6
# echo "aboba" > f1 > f2 > f3
< f7
# < f1 echo "hello" 
< f1 cat
< f1 f2 cat
#
# -- WORDS --
#
ls
ls /
ls -la
