
----------------------- GRAMMAR -------------------------------

<statement> 		::= <list> '\n' 

<list>				::= <pipeline> {('&&' | '||') <pipeline>}*

<pipeline> 			::= <expression> { '|' <expression> }*

<expression> 		::= {<word> | <redirection>}* 
					  | <group> <redirection>*

<group> 			::= '(' <list> ')'

<redirection>		::=  '>' <word>
               		  |  '<' <word>
               		  |  '>>' <word>
               		  |  '<<' <word>

<word> 				::= 'characters'

--------------------------TOKENS------------------------------
'"'
'\''
'('
')'
'&&'
'|'
'||'
'>'
'>>'
'<'
'<<'
