
----------------------- GRAMMAR -------------------------------

<statement> 		::= <list> '\n' 

<list>				::= <pipeline> {('&&' | '||') <pipeline>}*

<pipeline> 			::= <expression> { '|' <expression> }*

<expression> 		::= {<word> | <redirection>}* 
					  | <group> <redirection>*

<group> 			::= '(' <list> ')'

<redirection>		::=  '>' <word>
               		  |  '<' <word>
               		  |  '>>' <word>
               		  |  '<<' <word>

<word> 				::= 'a-z' '' "" 

------------------------------CASES----------------------------

max args
$ getconf ARG_MAX
2097152

-- quotes --
$ ls "/"'h''o''m'"'e'"
ls: cannot access "/hom'e'": No such file or directory

