


<cmdline> ::= <andor>
			| <group>
			| <pipeline>
			| <sequence>
			| <command>

<andor> ::= <cmdline> "&&" <cmdline> 
		|   <cmdline> "||" <cmdline>
<group> ::= '(' <cmdline> ')'
<pipeline> ::= <cmdline> '|' <cmdline>
<sequence> ::= <cmdline> ';' <cmdline>
<command> ::= <builtin> <args>
			| <executable> <args>

<args> ::= <arg> 
		|  <arg> <args>

<arg> ::= <string>
        | '"' <string> '"'
        | '\'' <string> '\''
<executable> ::= <path>
<builtin> ::= "echo" | "cd" 

<redirection> ::=  '>' <word>
                |  '<' <word>
                |  <number> '>' <word>
                |  <number> '<' <word>
                |  '>>' <word>
                |  <number> '>>' <word>
                |  '<<' <word>
                |  <number> '<<' <word>
                |  '<&' <number>
                |  <number> '<&' <number>
                |  '>&' <number>
                |  <number> '>&' <number>
                |  '<&' <word>
                |  <number> '<&' <word>
                |  '>&' <word>
                |  <number> '>&' <word>
                |  '<<-' <word>
                |  <number> '<<-' <word>
                |  '>&' '-'
                |  <number> '>&' '-'
                |  '<&' '-'
                |  <number> '<&' '-'
                |  '&>' <word>
                |  <number> '<>' <word>
                |  '<>' <word>
                |  '>|' <word>
                |  <number> '>|' <word>


------------------------------------------------------------
