
----------------------- GRAMMAR -------------------------------

<statement> 		::= <list> '\n' 

<list>				::= <pipeline> {('&&' | '||') <pipeline>}*

<pipeline> 			::= <expression> { '|' <expression> }*

<expression> 		::= {<word> | <redirection>}* 
					  | <group> <redirection>*

<group> 			::= '(' <list> ')'

<redirection>		::=  '>' <word>
               		  |  '<' <word>
               		  |  '>>' <word>
               		  |  '<<' <word>

<word> 				::= 'a-z' '' "" 

------------------------------CASES----------------------------

-- list --

$ 

-- group --

$ (ls | cat)
$ (echo "abiba" > f3)
$ ls && ls | cat # treated as ls && (ls | cat)

-- pipeline --

$ cat | ls #cat waits for input and ctrl-c

-- expression --

$ (echo "abiba" > f1)
$ echo "hello"

-- redirection (expression)--

# <word> <redir> <word> 
$ ls > f1 -la #works as ordinary ls -la > f1
# <redir> <word> <word> 
$ > f1 echo "hello"
# <word> <redir> <word> 
$ ls > f1
# <redir> 
$ > f1 #empty file
# <redir> <redir> <redir> 
$ > f4 > f5 > f6 #all empty files, it deletes the content of the file
# <word> <word> <redir> <redir> <redir> 
$ echo "aboba" > f1 > f2 > f3
# <redir> 
$ < f7 #bash: f7: No such file or directory, does not create the file
# <redir> <word> <word>
$ < f1 echo "hello" 
# <redir> <word>
$ < f1 cat
# <redir> <word> <word>
$ < f1 f2 cat  #f2: command not found
$ << EOF #bash ignores
$ << EOF > file #bash ignores
$ cat << EOF > file

$ (sleep 1 | ls) > f f2 #bash: syntax error near unexpected token `f2'
$ echo "aboba" > f1 > f2 > f3 ls -la


-- word (expression)--

$ ls
$ ls -la

-----------------------------------------------------------------
max args
$ getconf ARG_MAX
2097152

-- quotes --
$ ls "/"'h''o''m'"'e'"
ls: cannot access "/hom'e'": No such file or directory